title: Eric Mabicka
description: >- 
  Data Analyst based in Zurich, Switzerland | Applied Economics | Business Insights
theme: jekyll-theme-minimal
author: Eric Mabicka
github:
  is_project_page: false
show_downloads: false
